### ISSUE TITLE
ERR_SOCKET_BAD_PORT

### ISSUE THREAD

**Issue by ectasyxxx** [Maks-gaming/mineflayer-plasmovoice#58]
RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received undefined.
    at Socket.send (node:dgram:633:12)
    at PingPacket.send (C:\Users\neverdie\node_modules\mineflayer-plasmovoice\lib\packet\socket\PacketSocketBase.js:28:46)
    at C:\Users\neverdie\node_modules\mineflayer-plasmovoice\lib\packet\PacketSocketHandler.js:37:29
    at node:dgram:442:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_SOCKET_BAD_PORT'
}

**Comment by Maks-gaming** [comment]
enable debug and send me full log please

**Comment by ectasyxxx** [comment]
I reinstalled and got the following error: Cannot find module 'C:\Users\neverdie\node_modules\@discordjs\opus\prebuild\node-v120-napi-v3-win32-x64-unknown-unknown\opus.node'

**Comment by ectasyxxx** [comment]
the folder contains only "node-v93-napi-v3-win32-x64-unknown-unknown"

**Comment by Maks-gaming** [comment]
this should help
https://stackoverflow.com/questions/65896154/error-cannot-find-module-discordjs-opus

**Comment by ectasyxxx** [comment]
![Снимок экрана 2024-04-03 220048](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/165364984/3a68ebef-c260-4625-bb1d-887163468a87)
using plugin v1.3.1a
minecraft server on localhost 1.20.1

**Comment by ectasyxxx** [comment]
but a new problem has arisen
![изображение](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/165364984/ae0a9cb2-33c9-43f7-96cd-681b0c67fe99)
**code:**
const mineflayer = require("mineflayer")
const plasmo = require("mineflayer-plasmovoice")

const bot = mineflayer.createBot({
    "host": "localhost"
})

bot.loadPlugin(plasmo.plugin)

bot.on("voicechat_connected", () => {
    bot.setControlState("sneak", true)

})

bot.on("voicechat_audio_end", () => {
    bot.setControlState("sneak", false)
})

bot.on('chat', (username, message) => {
    if (username === 'neverdi3x' && message.includes('play')) {
        bot.plasmovoice.sendAudio("music.mp3")
    }
  });

**Comment by RizzProfessor5** [comment]
How did you fix it?

**Comment by Humpfry** [comment]
Getting the same error, tried 1.20.4, then 1.20.1.. same error as OP.

**Comment by Maks-gaming** [comment]
> Getting the same error, tried 1.20.4, then 1.20.1.. same error as OP. Where is the full log? or how do I get the debug output if it is not turned on.

`plasmo.setLoggingLevel(0);`

**Comment by RizzProfessor5** [comment]
This is the logs I get
```
2024-04-15 13:09:04.472 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketClientHandler.js:31       Registering client packet encoder
2024-04-15 13:09:04.474 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:15       Registering mod packet data..
2024-04-15 13:09:04.475 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:19       Waiting for login..
2024-04-15 13:09:04.475 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketClientHandler.js:33       Registering client packets
2024-04-15 13:09:04.476 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketSocketHandler.js:25       Registering socket packet encoder
2024-04-15 13:09:05.221 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:21       Logged in!
2024-04-15 13:09:05.222 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:23       Registering channels..
2024-04-15 13:09:05.224 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:28       Registering types..
2024-04-15 13:09:06.054 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:19   Client RECEIVE PlayerInfoRequestPacket
2024-04-15 13:09:06.055 SILLY   \node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:20   Client {}
2024-04-15 13:09:06.056 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:25   Client SEND PlayerInfoPacket
2024-04-15 13:09:06.057 SILLY   \node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:26   Client {
  voiceDisabled: false,
  microphoneMuted: false,
  minecraftVersion: '1.20.4',
  version: '2.0.8',
  publicKey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 cf b7 77 76 78 f6 c5 24 90 28 38 9c 44 9b 0f 30 12 ... 244 more bytes>
}
2024-04-15 13:09:06.261 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:19   Client RECEIVE ConnectionPacket
2024-04-15 13:09:06.262 SILLY   \node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:20   Client {
  secret: {
    mostSignificantBits: 14611258382635123995n,
    lessSignificantBits: 11504181977939127935n
  },
  ip: '0.0.0.0',
  port: 49511
}
2024-04-15 13:09:06.265 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\PacketSocketHandler.js:35       Socket Connected to the socket
2024-04-15 13:09:06.266 DEBUG   \node_modules\mineflayer-plasmovoice\lib\packet\socket\PacketSocketBase.js:26   Socket SEND PingPacket
2024-04-15 13:09:06.266 SILLY   \node_modules\mineflayer-plasmovoice\lib\packet\socket\PacketSocketBase.js:27   Socket {
  currentTime: 1713186546265n
}
node:internal/validators:409
    throw new ERR_SOCKET_BAD_PORT(name, port, allowZero);
    ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received undefined.
    at new NodeError (node:internal/errors:405:5)
    at validatePort (node:internal/validators:409:11)
    at Socket.send (node:dgram:633:12)
    at PingPacket.send (C:\Users\admin\plasmomineflayer\node_modules\mineflayer-plasmovoice\lib\packet\socket\PacketSocketBase.js:28:46)
    at C:\Users\admin\plasmomineflayer\node_modules\mineflayer-plasmovoice\lib\packet\PacketSocketHandler.js:37:29
    at node:dgram:442:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_SOCKET_BAD_PORT'
}

Node.js v18.20.2
```

**Comment by Maks-gaming** [comment]
got you guys, I'll fix it in three days, as I'm finishing the order now

**Comment by Humpfry** [comment]
2024-04-15 23:22:00.745	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketClientHandler.js:31	Registering client packet encoder
2024-04-15 23:22:00.749	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:15	Registering mod packet data..
2024-04-15 23:22:00.750	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:19	Waiting for login..
2024-04-15 23:22:00.750	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketClientHandler.js:33	Registering client packets
2024-04-15 23:22:00.750	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketSocketHandler.js:25	Registering socket packet encoder
2024-04-15 23:22:01.157	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:21	Logged in!
2024-04-15 23:22:01.158	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:23	Registering channels..
2024-04-15 23:22:01.160	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketClientEncoder.js:28	Registering types..


'Login plasmo: False'  <  ----- output  line 59 of python code inside @On(bot, 'login') ->  pp(f"Login plasmo: {bot.plasmovoice.isLaunched()}")


2024-04-15 23:22:03.834	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:19	Client	RECEIVE PlayerInfoRequestPacket
2024-04-15 23:22:03.834	SILLY	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:20	Client	{}
2024-04-15 23:22:03.835	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:25	Client	SEND PlayerInfoPacket
2024-04-15 23:22:03.835	SILLY	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:26	Client	{
  voiceDisabled: false,
  microphoneMuted: false,
  minecraftVersion: '1.20.1',
  version: '2.0.8',
  publicKey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 90 7c 12 78 9b f6 a4 4a be cd 22 f8 ed 4e 22 88 d3 ... 244 more bytes>
}
2024-04-15 23:22:03.856	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:19	Client	RECEIVE ConnectionPacket
2024-04-15 23:22:03.856	SILLY	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\client\ClientPacketBase.js:20	Client	{
  secret: {
    mostSignificantBits: 8498030282547217878n,
    lessSignificantBits: 13177482663133605802n
  },
  ip: '0.0.0.0',
  port: 56079
}
2024-04-15 23:22:03.859	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketSocketHandler.js:35	Socket	Connected to the socket
2024-04-15 23:22:03.860	DEBUG	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\socket\PacketSocketBase.js:26	Socket	SEND PingPacket
2024-04-15 23:22:03.860	SILLY	\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\socket\PacketSocketBase.js:27	Socket	{
  currentTime: 1713223323860n
}
[JSE] node:internal/errors:541
[JSE]       throw error;
[JSE]       ^
[JSE] 
[JSE] RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received undefined.
[JSE]     at Socket.send (node:dgram:633:12)
[JSE]     at PingPacket.send (C:\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\socket\PacketSocketBase.js:28:46)
[JSE]     at C:\Users\humpf\PycharmProjects\mcbot\.venv\Lib\site-packages\javascript\js\node_modules\mineflayer-plasmovoice\lib\packet\PacketSocketHandler.js:37:29
[JSE]     at node:dgram:442:9
[JSE]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
[JSE]   code: 'ERR_SOCKET_BAD_PORT'
[JSE] }
[JSE] 
[JSE] Node.js v20.12.2

**Comment by Maks-gaming** [comment]
The commit 4cf3c93 solved the issue
